### ISSUE TITLE
Integrate testing suite

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#673]
Have the tests perform on every merge / PR creation

**Comment by benefacto** [comment]
This is a priority immediately after my onboarding.

**Comment by benefacto** [comment]
Duplicate issue: https://app.zenhub.com/workspaces/tezos-homebase-63238426ddf385159a4c4b12/issues/gh/dorgtech/homebase-app/702

**Comment by benefacto** [comment]
Tests being referred to seem to be in this repository: https://github.com/W3DevTeam/TezosHomebaseTests
Below is a good example of a GitHub action that could be run (would have to be adapted for Netlify). 
```yaml
name: Playwright Tests
on:
  deployment_status:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
```
Playwright has good documentation to execute on this: https://playwright.dev/docs/ci-intro
